use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::Path;

use anyhow::{anyhow, Context, Result};
use roxmltree::{Document, Node};

use crate::docx::{DocxPackage, Relationship};
use crate::figure;
use crate::job::{display_path, ConversionJob};
use crate::markdown;
use crate::types::UnsupportedAsset;
use crate::word::{
    collect_inline_text, collect_media_refs, heading_level_from_style_id,
    heading_level_from_style_name, is_w_tag, numeric_heading_level, paragraph_numbering,
    paragraph_style_id, Numbering, StyleMap,
};

#[derive(Debug, Clone)]
struct AssetLink {
    source_path: String,
    output_path: String,
    link_path: String,
    file_name: String,
    extension: String,
    supported: bool,
}

pub(crate) struct Renderer<'a> {
    package: &'a mut DocxPackage,
    job: &'a ConversionJob,
    relationships: HashMap<String, Relationship>,
    styles: StyleMap,
    numbering: Numbering,
    copied_assets: HashMap<String, AssetLink>,
    used_file_names: HashSet<String>,
    pub(crate) paragraph_count: usize,
    pub(crate) table_count: usize,
    pub(crate) media_count: usize,
    pub(crate) unsupported_assets: Vec<UnsupportedAsset>,
    pub(crate) warnings: Vec<String>,
}

impl<'a> Renderer<'a> {
    pub(crate) fn new(
        package: &'a mut DocxPackage,
        job: &'a ConversionJob,
        relationships: HashMap<String, Relationship>,
        styles: StyleMap,
        numbering: Numbering,
    ) -> Self {
        Self {
            package,
            job,
            relationships,
            styles,
            numbering,
            copied_assets: HashMap::new(),
            used_file_names: HashSet::new(),
            paragraph_count: 0,
            table_count: 0,
            media_count: 0,
            unsupported_assets: Vec::new(),
            warnings: Vec::new(),
        }
    }

    pub(crate) fn render_document(&mut self, document: &Document<'_>) -> Result<String> {
        let body = document
            .descendants()
            .find(|node| is_w_tag(*node, "body"))
            .ok_or_else(|| anyhow!("DOCX document has no w:body"))?;

        let mut blocks = Vec::new();
        for child in body.children().filter(Node::is_element) {
            if is_w_tag(child, "p") {
                if let Some(block) = self.render_paragraph(child)? {
                    blocks.push(block);
                }
            } else if is_w_tag(child, "tbl") {
                if let Some(block) = self.render_table(child) {
                    blocks.push(block);
                }
            }
        }

        let mut output = String::from("<!-- Generated by proposal2md. -->\n\n");
        output.push_str(&blocks.join("\n\n"));
        output.push('\n');
        Ok(output)
    }

    fn render_paragraph(&mut self, paragraph: Node<'_, '_>) -> Result<Option<String>> {
        let text = markdown::normalize_paragraph_text(&collect_inline_text(paragraph));
        let media_refs = collect_media_refs(paragraph);

        if text.is_empty() && media_refs.is_empty() {
            return Ok(None);
        }

        self.paragraph_count += 1;
        let mut blocks = Vec::new();

        if !text.is_empty() {
            if let Some(level) = self.heading_level(paragraph, &text) {
                blocks.push(format!("{} {}", "#".repeat(level), text));
            } else if let Some(list_item) = self.render_list_item(paragraph, &text) {
                blocks.push(list_item);
            } else {
                blocks.push(text);
            }
        }

        if let Some(media_block) = self.render_media_refs(&media_refs)? {
            blocks.push(media_block);
        }

        Ok(Some(blocks.join("\n\n")))
    }

    fn render_table(&mut self, table: Node<'_, '_>) -> Option<String> {
        let mut rows = Vec::new();

        for row in table.children().filter(|node| is_w_tag(*node, "tr")) {
            let mut cells = Vec::new();
            for cell in row.children().filter(|node| is_w_tag(*node, "tc")) {
                let mut parts = Vec::new();
                for paragraph in cell.children().filter(|node| is_w_tag(*node, "p")) {
                    let text = markdown::normalize_cell_text(&collect_inline_text(paragraph));
                    if !text.is_empty() {
                        parts.push(text);
                    }
                }
                cells.push(markdown::escape_table_cell(&parts.join("<br>")));
            }
            if !cells.is_empty() {
                rows.push(cells);
            }
        }

        if rows.is_empty() {
            return None;
        }

        self.table_count += 1;
        let width = rows.iter().map(Vec::len).max().unwrap_or(0);
        for row in &mut rows {
            row.resize(width, String::new());
        }

        let mut lines = Vec::new();
        lines.push(markdown::table_row(&rows[0]));
        lines.push(markdown::table_separator(width));
        for row in rows.iter().skip(1) {
            lines.push(markdown::table_row(row));
        }

        Some(lines.join("\n"))
    }

    fn render_media_refs(&mut self, refs: &[String]) -> Result<Option<String>> {
        if refs.is_empty() {
            return Ok(None);
        }

        let mut assets = Vec::new();
        for relationship_id in self.preferred_figure_refs(refs) {
            if let Some(asset) = self.copy_relationship_asset(relationship_id)? {
                assets.push(asset);
            }
        }

        if assets.is_empty() {
            return Ok(None);
        }

        let mut blocks = Vec::new();
        for asset in assets.iter().filter(|asset| asset.supported) {
            blocks.push(format!(
                "![{}]({})",
                markdown::alt_text(&asset.file_name),
                markdown::link_target(&asset.link_path)
            ));
        }

        let unsupported = assets
            .iter()
            .filter(|asset| !asset.supported)
            .collect::<Vec<_>>();
        if !unsupported.is_empty() {
            let mut lines =
                vec!["> **Unsupported figure:** extracted original asset(s):".to_string()];
            for asset in unsupported {
                lines.push(format!(
                    "> - [{}]({}) ({})",
                    asset.file_name,
                    markdown::link_target(&asset.link_path),
                    asset.extension
                ));
            }
            blocks.push(lines.join("\n"));
        }

        Ok(Some(blocks.join("\n\n")))
    }

    fn preferred_figure_refs<'refs>(&self, refs: &'refs [String]) -> Vec<&'refs str> {
        let image_refs = refs
            .iter()
            .filter(|id| {
                self.relationships
                    .get(*id)
                    .is_some_and(|relationship| relationship.relationship_type.ends_with("/image"))
            })
            .map(String::as_str)
            .collect::<Vec<_>>();

        if image_refs.is_empty() {
            refs.iter().map(String::as_str).collect()
        } else {
            image_refs
        }
    }

    fn copy_relationship_asset(&mut self, relationship_id: &str) -> Result<Option<AssetLink>> {
        let Some(relationship) = self.relationships.get(relationship_id).cloned() else {
            self.warnings.push(format!(
                "missing relationship for media id {relationship_id}"
            ));
            return Ok(None);
        };

        if relationship.target_mode.as_deref() == Some("External") {
            self.warnings.push(format!(
                "external relationship skipped: {} -> {}",
                relationship.id, relationship.target
            ));
            return Ok(None);
        }

        let Some(zip_path) = relationship.zip_path.clone() else {
            self.warnings.push(format!(
                "relationship {} has no package target: {}",
                relationship.id, relationship.target
            ));
            return Ok(None);
        };

        if let Some(asset) = self.copied_assets.get(&zip_path) {
            return Ok(Some(asset.clone()));
        }

        let bytes = match self.package.read_bytes(&zip_path) {
            Ok(bytes) => bytes,
            Err(error) => {
                self.warnings.push(format!(
                    "failed to read asset {} for {}: {error}",
                    zip_path, relationship.id
                ));
                return Ok(None);
            }
        };

        let source_name = Path::new(&zip_path)
            .file_name()
            .and_then(|name| name.to_str())
            .ok_or_else(|| anyhow!("asset path has no file name: {zip_path}"))?;
        let source_extension = Path::new(source_name)
            .extension()
            .and_then(|ext| ext.to_str())
            .unwrap_or("unknown")
            .to_ascii_lowercase();

        let converted_png = if figure::can_convert_to_png(&source_extension) {
            let png_name = self.unique_asset_file_name_with_extension(&zip_path, "png")?;
            let temp_source_name = Path::new(&png_name)
                .with_extension(&source_extension)
                .file_name()
                .and_then(|name| name.to_str())
                .unwrap_or(source_name)
                .to_string();
            match figure::convert_to_png(&bytes, &temp_source_name, &self.job.asset_dir, &png_name)
            {
                Ok(output_path) => Some((png_name, output_path)),
                Err(error) => {
                    self.warnings.push(format!(
                        "PNG conversion failed for {}: {error}",
                        relationship.target
                    ));
                    None
                }
            }
        } else {
            None
        };

        let (file_name, output_path) = if let Some((file_name, output_path)) = converted_png {
            (file_name, output_path)
        } else {
            let file_name = self.unique_asset_file_name(&zip_path)?;
            let output_path = self.job.asset_dir.join(&file_name);
            fs::write(&output_path, bytes)
                .with_context(|| format!("failed to write asset {}", output_path.display()))?;
            (file_name, output_path)
        };

        let extension = Path::new(&file_name)
            .extension()
            .and_then(|ext| ext.to_str())
            .unwrap_or("unknown")
            .to_ascii_lowercase();
        let supported = markdown::is_supported_image(&extension);
        let link_path = format!("{}/{}", self.job.asset_link_prefix, file_name);

        let asset = AssetLink {
            source_path: zip_path.clone(),
            output_path: display_path(&output_path),
            link_path,
            file_name,
            extension,
            supported,
        };

        self.media_count += 1;
        if !asset.supported {
            self.unsupported_assets.push(UnsupportedAsset {
                relationship_id: relationship.id,
                kind: markdown::media_kind(&relationship.relationship_type, &asset.extension)
                    .to_string(),
                source_path: asset.source_path.clone(),
                output_path: asset.output_path.clone(),
            });
        }

        self.copied_assets.insert(zip_path, asset.clone());
        Ok(Some(asset))
    }

    fn unique_asset_file_name(&mut self, zip_path: &str) -> Result<String> {
        let path = Path::new(zip_path);
        let extension = path.extension().and_then(|ext| ext.to_str()).unwrap_or("");
        self.unique_asset_file_name_with_extension(zip_path, extension)
    }

    fn unique_asset_file_name_with_extension(
        &mut self,
        zip_path: &str,
        extension: &str,
    ) -> Result<String> {
        let path = Path::new(zip_path);
        let base_name = path
            .file_stem()
            .and_then(|name| name.to_str())
            .ok_or_else(|| anyhow!("asset path has no file stem: {zip_path}"))?;

        let mut candidate = if extension.is_empty() {
            base_name.to_string()
        } else {
            format!("{base_name}.{extension}")
        };
        if self.used_file_names.insert(candidate.clone()) {
            return Ok(candidate);
        }

        for index in 2usize.. {
            candidate = if extension.is_empty() {
                format!("{base_name}_{index}")
            } else {
                format!("{base_name}_{index}.{extension}")
            };
            if self.used_file_names.insert(candidate.clone()) {
                return Ok(candidate);
            }
        }

        unreachable!("unbounded filename search should always return")
    }

    fn heading_level(&self, paragraph: Node<'_, '_>, text: &str) -> Option<usize> {
        if let Some(style_id) = paragraph_style_id(paragraph) {
            if let Some(level) = heading_level_from_style_id(&style_id) {
                return Some(level);
            }
            if let Some(style) = self.styles.styles.get(&style_id) {
                if let Some(level) = heading_level_from_style_name(&style.name) {
                    return Some(level);
                }
            }
        }

        numeric_heading_level(text)
    }

    fn render_list_item(&self, paragraph: Node<'_, '_>, text: &str) -> Option<String> {
        if let Some((num_id, ilvl)) = paragraph_numbering(paragraph) {
            let depth = ilvl.parse::<usize>().unwrap_or(0);
            let indent = "  ".repeat(depth);
            let marker = match self.numbering.format_for(&num_id, &ilvl) {
                Some("bullet") => "-",
                _ => "1.",
            };
            return Some(format!(
                "{indent}{marker} {}",
                markdown::trim_existing_list_marker(text)
            ));
        }

        let trimmed = text.trim_start();
        if let Some(rest) = trimmed.strip_prefix('-') {
            return Some(format!("- {}", rest.trim_start()));
        }
        if let Some(rest) = trimmed.strip_prefix('•') {
            return Some(format!("- {}", rest.trim_start()));
        }

        None
    }
}
